<a href="https://colab.research.google.com/github/magdalena-owczarek/portfolio/blob/main/colab_prices_real_estate_poland.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install dash

Requirement already satisfied: dash in /usr/local/lib/python3.10/dist-packages (2.17.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from dash) (2.2.5)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.10/dist-packages (from dash) (3.0.3)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from dash) (5.15.0)
Requirement already satisfied: dash-html-components==2.0.0 in /usr/local/lib/python3.10/dist-packages (from dash) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in /usr/local/lib/python3.10/dist-packages (from dash) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in /usr/local/lib/python3.10/dist-packages (from dash) (5.0.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from dash) (8.2.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from dash) (4.12.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in /usr/local/lib/python3.10/dist-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from dash) (71.0.4)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.7)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=5.0.0->dash) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=5.0.0->dash) (24.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from Werkzeug<3.1->dash) (2.1.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->dash) (3.19.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (2024.7.4)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from retrying->dash) (1.16.0)

In [2]:
# Import the necessary module to access Google Drive
from google.colab import drive

# Mount Google Drive to the Colab environment
# This will allow you to access files stored in your Google Drive
drive.mount('/content/drive')

# The path '/content/drive/My Drive/' represents the root directory of your Google Drive in Colab.
# You can then access files in your Drive using this path.

# Importing pandas for data manipulation and analysis
import pandas as pd

# Importing plotly.express for creating interactive plots and visualizations
import plotly.express as px

# Importing Dash and its components to create interactive web applications
import dash
from dash import html, dcc, Input, Output

# Importing threading to enable concurrent execution in the application if needed
import threading

# Import output module from google.colab
from google.colab import output

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Define the path to your Excel file within Google Drive
# This path is specific to where the file is located in Google Drive
file_path = '/content/drive/My Drive/coderslab/data/ceny_mieszkan.xlsx'

# Read the Excel file into a DataFrame using pandas
# Specify the sheet name from which to read the data
# The 'sheet_name' parameter should match the exact name of the sheet in your Excel file
primary_market_offer_prices_df = pd.read_excel(
    file_path,  # Path to the Excel file
    sheet_name='Rynek pierwotny - ceny ofertowe'  # Name of the sheet to be read
)

# Display the first few rows of the DataFrame
# This allows you to preview the data and ensure it has been loaded correctly
primary_market_offer_prices_df.head()

,Kwartał,Białystok,Bydgoszcz,Gdańsk,Gdynia,Katowice,Kielce,Kraków,Lublin,Łódź,Olsztyn,Opole,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław,Zielona Góra
0,III 2006,2727.0,3243.0,5004.0,4937.0,3986.27,2918.644443,6021.0,3456.0,3210.0,4000.0,3342.843092,4769.933415,2862.0,3214.980636,5873.0,4750.000000,2754.275993
1,IV 2006,2727.0,3947.0,6199.0,5284.0,4062.31,3492.617589,7929.0,3314.0,4237.0,4800.0,NaN,4827.227500,3401.0,3679.123336,6095.0,5759.000000,2869.297734
2,I 2007,4181.0,4501.0,6437.0,6466.0,4518.37,3381.718956,8247.0,3604.0,4927.0,5149.0,NaN,7274.746093,3420.0,4749.124321,7509.0,6308.702547,2871.939482
3,II 2007,4725.0,5700.0,7999.0,8934.0,5180.56,3901.578310,8129.0,4143.0,5453.0,4776.0,NaN,7360.018661,4080.0,5049.969372,8000.0,6294.000000,4153.489905
4,III 2007,4199.0,4994.0,8053.0,8114.0,6235.53,4651.056569,8420.0,4645.0,5201.0,4900.0,4784.143691,6837.761370,4069.0,5034.720763,8740.0,6444.287532,4207.569891

In [4]:
# Display the column names of the DataFrame
primary_market_offer_prices_df.columns

Index(['Kwartał', 'Białystok', 'Bydgoszcz', 'Gdańsk', 'Gdynia', 'Katowice',
       'Kielce', 'Kraków', 'Lublin', 'Łódź', 'Olsztyn', 'Opole', 'Poznań',
       'Rzeszów', 'Szczecin', 'Warszawa', 'Wrocław', 'Zielona Góra'],
      dtype='object')

In [5]:
# Dictionary to map Polish column names to English column names
column_translation = {
    'Kwartał': 'Quarter',          # 'Kwartał' in Polish translates to 'Quarter' in English
    'Białystok': 'Bialystok',     # 'Białystok' in Polish translates to 'Bialystok' in English
    'Bydgoszcz': 'Bydgoszcz',     # 'Bydgoszcz' remains 'Bydgoszcz' in English
    'Gdańsk': 'Gdansk',           # 'Gdańsk' in Polish translates to 'Gdansk' in English
    'Gdynia': 'Gdynia',           # 'Gdynia' remains 'Gdynia' in English
    'Katowice': 'Katowice',       # 'Katowice' remains 'Katowice' in English
    'Kielce': 'Kielce',           # 'Kielce' remains 'Kielce' in English
    'Kraków': 'Krakow',           # 'Kraków' in Polish translates to 'Krakow' in English
    'Lublin': 'Lublin',           # 'Lublin' remains 'Lublin' in English
    'Łódź': 'Lodz',               # 'Łódź' in Polish translates to 'Lodz' in English
    'Olsztyn': 'Olsztyn',         # 'Olsztyn' remains 'Olsztyn' in English
    'Opole': 'Opole',             # 'Opole' remains 'Opole' in English
    'Poznań': 'Poznan',           # 'Poznań' in Polish translates to 'Poznan' in English
    'Rzeszów': 'Rzeszow',         # 'Rzeszów' in Polish translates to 'Rzeszow' in English
    'Szczecin': 'Szczecin',       # 'Szczecin' remains 'Szczecin' in English
    'Warszawa': 'Warsaw',         # 'Warszawa' in Polish translates to 'Warsaw' in English
    'Wrocław': 'Wroclaw',         # 'Wrocław' in Polish translates to 'Wroclaw' in English
    'Zielona Góra': 'Zielona Gora'  # 'Zielona Góra' in Polish translates to 'Zielona Gora' in English
}

# Rename columns in the DataFrame according to the translation dictionary
primary_market_offer_prices_df.rename(columns=column_translation, inplace=True)

# Display the first row of the DataFrame to verify the column name changes
primary_market_offer_prices_df.head(1)

,Quarter,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
0,III 2006,2727.0,3243.0,5004.0,4937.0,3986.27,2918.644443,6021.0,3456.0,3210.0,4000.0,3342.843092,4769.933415,2862.0,3214.980636,5873.0,4750.0,2754.275993

In [6]:
# Round all numerical columns in the DataFrame to the nearest integer
primary_market_offer_prices_df = primary_market_offer_prices_df.round(0)

# Display the first few rows of the DataFrame to check the result
primary_market_offer_prices_df.head()

,Quarter,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
0,III 2006,2727.0,3243.0,5004.0,4937.0,3986.0,2919.0,6021.0,3456.0,3210.0,4000.0,3343.0,4770.0,2862.0,3215.0,5873.0,4750.0,2754.0
1,IV 2006,2727.0,3947.0,6199.0,5284.0,4062.0,3493.0,7929.0,3314.0,4237.0,4800.0,NaN,4827.0,3401.0,3679.0,6095.0,5759.0,2869.0
2,I 2007,4181.0,4501.0,6437.0,6466.0,4518.0,3382.0,8247.0,3604.0,4927.0,5149.0,NaN,7275.0,3420.0,4749.0,7509.0,6309.0,2872.0
3,II 2007,4725.0,5700.0,7999.0,8934.0,5181.0,3902.0,8129.0,4143.0,5453.0,4776.0,NaN,7360.0,4080.0,5050.0,8000.0,6294.0,4153.0
4,III 2007,4199.0,4994.0,8053.0,8114.0,6236.0,4651.0,8420.0,4645.0,5201.0,4900.0,4784.0,6838.0,4069.0,5035.0,8740.0,6444.0,4208.0

In [7]:
# Read the Excel file into a DataFrame using pandas
# Specify the sheet name from which to read the data
# The 'sheet_name' parameter should match the exact name of the sheet in your Excel file
primary_market_transaction_prices_df = pd.read_excel(
    file_path,  # Path to the Excel file
    sheet_name='Rynek pierwotny - ceny transak'  # Name of the sheet to be read
)

# Round all numerical columns in the DataFrame to the nearest integer
primary_market_transaction_prices_df = primary_market_transaction_prices_df.round(0)

# Rename columns in the DataFrame according to the translation dictionary
primary_market_transaction_prices_df.rename(columns=column_translation, inplace=True)

# Display the first few rows of the DataFrame to check the result
primary_market_transaction_prices_df.head()

,Quarter,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
0,III 2006,3008.0,2663.0,3494.0,4467.0,3523.0,2835.0,6816.0,3022.0,2860.0,2640.0,3299.0,3621.0,2656.0,3234.0,5605.0,3211.0,2499.0
1,IV 2006,3117.0,2811.0,5252.0,5284.0,3735.0,3014.0,7089.0,3304.0,3642.0,2869.0,3343.0,4726.0,3013.0,3575.0,6186.0,3777.0,2769.0
2,I 2007,3500.0,3017.0,5490.0,5797.0,3806.0,3241.0,7192.0,3309.0,4209.0,2960.0,NaN,6445.0,3469.0,3831.0,7302.0,7063.0,2500.0
3,II 2007,4422.0,4092.0,7137.0,6992.0,5094.0,3018.0,7856.0,3503.0,5403.0,3318.0,3307.0,7243.0,3517.0,4933.0,7523.0,5289.0,3258.0
4,III 2007,4651.0,4466.0,7440.0,7238.0,5698.0,4766.0,8060.0,4125.0,5212.0,3588.0,4253.0,5426.0,4124.0,5121.0,7879.0,5836.0,4015.0

In [8]:
# Read the Excel file into a DataFrame using pandas
# Specify the sheet name from which to read the data
# The 'sheet_name' parameter should match the exact name of the sheet in your Excel file
secondary_market_transaction_prices_df = pd.read_excel(
    file_path,  # Path to the Excel file
    sheet_name='Rynek wtórny - ceny transak'  # Name of the sheet to be read
)

# Round all numerical columns in the DataFrame to the nearest integer
secondary_market_transaction_prices_df = secondary_market_transaction_prices_df.round(0)

# Rename columns in the DataFrame according to the translation dictionary
secondary_market_transaction_prices_df.rename(columns=column_translation, inplace=True)

# Display the first few rows of the DataFrame to check the result
secondary_market_transaction_prices_df.head()

,Quarter,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
0,III 2006,2529.0,2424.0,3926.0,2782.0,2028.0,2355.0,5193.0,2769.0,1905.0,3126.0,2777.0,3332.0,2591.0,2888.0,6232.0,4734.0,1960.0
1,IV 2006,2998.0,2359.0,4072.0,4561.0,2160.0,2673.0,6349.0,2884.0,2160.0,3665.0,2885.0,3903.0,2935.0,3133.0,7143.0,4932.0,2381.0
2,I 2007,3590.0,2836.0,4787.0,4966.0,2542.0,3022.0,6267.0,3373.0,3360.0,4082.0,3295.0,4523.0,3916.0,3755.0,7730.0,5732.0,2264.0
3,II 2007,4009.0,3424.0,5806.0,5817.0,3013.0,3661.0,7309.0,3870.0,3749.0,4687.0,3771.0,5538.0,3918.0,4083.0,8696.0,6217.0,3126.0
4,III 2007,4635.0,3913.0,6059.0,6483.0,3870.0,3670.0,7193.0,4265.0,3981.0,4716.0,3958.0,5805.0,4073.0,4321.0,9137.0,6862.0,3483.0

In [9]:
# Read the Excel file into a DataFrame using pandas
# Specify the sheet name from which to read the data
# The 'sheet_name' parameter should match the exact name of the sheet in your Excel file
secondary_market_offer_prices_df = pd.read_excel(
    file_path,  # Path to the Excel file
    sheet_name='Rynek wtórny - ceny ofertowe'  # Name of the sheet to be read
)

# Round all numerical columns in the DataFrame to the nearest integer
secondary_market_offer_prices_df = secondary_market_offer_prices_df.round(0)

# Rename columns in the DataFrame according to the translation dictionary
secondary_market_offer_prices_df.rename(columns=column_translation, inplace=True)

# Display the first few rows of the DataFrame to check the result
secondary_market_offer_prices_df.head()

,Quarter,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
0,III 2006,3070.0,2530.0,4541.0,5756.0,2508.0,2425.0,7114.0,3160.0,2740.0,3414.0,3164.0,3752.0,2851.0,3190.0,7179.0,5261.0,2137.0
1,IV 2006,3408.0,2784.0,5406.0,6496.0,2649.0,3127.0,7383.0,3562.0,3316.0,3925.0,3585.0,4462.0,3734.0,3857.0,8751.0,5857.0,2384.0
2,I 2007,3986.0,3607.0,6115.0,7211.0,3704.0,3904.0,8369.0,3986.0,4130.0,5049.0,3349.0,6104.0,4187.0,4735.0,9316.0,6747.0,2993.0
3,II 2007,4418.0,3932.0,6602.0,6747.0,4152.0,4121.0,8272.0,4699.0,4609.0,5352.0,4150.0,6698.0,4647.0,4959.0,9740.0,7038.0,3199.0
4,III 2007,4580.0,4150.0,6740.0,7188.0,4151.0,4231.0,8255.0,4815.0,4721.0,5394.0,4136.0,6387.0,4814.0,5094.0,10078.0,7194.0,3565.0

In [10]:
# Generate a statistical summary of the numerical columns in the DataFrame
primary_market_offer_prices_df.describe()

,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,68.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,5626.690141,5942.957746,7878.281690,7879.197183,6580.408451,5421.676056,8205.478873,5872.690141,5873.549296,5700.718310,5570.029412,7363.464789,5407.070423,6270.943662,9379.816901,7282.774648,4525.704225
std,1545.526740,1530.102027,2145.280129,2018.600368,1721.417693,1265.582122,2152.284639,1670.652204,1563.266788,1326.478272,1402.006632,1588.479829,1639.220959,2212.635396,2136.345707,2125.648904,1400.203357
min,2727.000000,3243.000000,5004.000000,4937.000000,3986.000000,2919.000000,6021.000000,3314.000000,3210.000000,4000.000000,3343.000000,4770.000000,2862.000000,3215.000000,5873.000000,4750.000000,2754.000000
25%,4826.500000,4939.500000,6378.000000,6327.500000,5445.000000,4841.000000,6733.000000,5037.000000,4934.000000,4803.000000,4783.250000,6444.000000,4278.500000,4923.500000,7876.500000,6059.500000,3683.500000
50%,4949.000000,5153.000000,6775.000000,6944.000000,6085.000000,4958.000000,7559.000000,5172.000000,5250.000000,4971.000000,4955.500000,6725.000000,5027.000000,5206.000000,8551.000000,6342.000000,3891.000000
75%,5938.500000,6469.500000,9547.500000,9224.500000,6859.500000,5436.000000,8475.000000,5922.000000,6150.500000,6270.500000,5956.500000,7510.500000,5839.500000,6590.000000,10136.500000,7942.500000,4773.000000
max,9941.000000,9941.000000,13827.000000,12766.000000,11342.000000,9034.000000,15630.000000,10880.000000,10708.000000,9787.000000,10064.000000,12803.000000,10264.000000,12391.000000,16191.000000,13531.000000,8165.000000

In [11]:
# Get a concise summary of the DataFrame, including data types and non-null counts
primary_market_offer_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Quarter       71 non-null     object
 1   Bialystok     71 non-null     float64
 2   Bydgoszcz     71 non-null     float64
 3   Gdansk        71 non-null     float64
 4   Gdynia        71 non-null     float64
 5   Katowice      71 non-null     float64
 6   Kielce        71 non-null     float64
 7   Krakow        71 non-null     float64
 8   Lublin        71 non-null     float64
 9   Lodz          71 non-null     float64
 10  Olsztyn       71 non-null     float64
 11  Opole         68 non-null     float64
 12  Poznan        71 non-null     float64
 13  Rzeszow       71 non-null     float64
 14  Szczecin      71 non-null     float64
 15  Warsaw        71 non-null     float64
 16  Wroclaw       71 non-null     float64
 17  Zielona Gora  71 non-null     float64
dtypes: float64(17), object(1)
memory usage: 10.1+ KB

In [12]:
# Generate a statistical summary of the numerical columns in the DataFrame
primary_market_transaction_prices_df.describe()

,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,70.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,5376.239437,5474.309859,7281.605634,7272.788732,5949.859155,5202.957746,7761.690141,5623.732394,5556.084507,5299.830986,5159.157143,6972.845070,5200.394366,5993.084507,8727.126761,6873.619718,4387.056338
std,1444.191306,1420.656092,2132.035945,1710.534586,1718.584611,1271.926822,1960.793044,1583.908222,1407.530063,1362.591355,1584.942852,1454.338138,1488.439609,2031.581416,2156.383493,2006.105726,1353.452969
min,3008.000000,2663.000000,3494.000000,4467.000000,3523.000000,2835.000000,5722.000000,3022.000000,2860.000000,2640.000000,3299.000000,3621.000000,2656.000000,3234.000000,5605.000000,3211.000000,2499.000000
25%,4573.500000,4630.500000,5687.000000,6054.500000,4910.500000,4611.500000,6517.000000,4807.500000,4681.500000,4493.500000,4354.000000,6202.000000,4196.500000,4755.000000,7443.500000,5626.500000,3653.000000
50%,4802.000000,4855.000000,6430.000000,6710.000000,5217.000000,4778.000000,6981.000000,4980.000000,5066.000000,4896.000000,4648.000000,6430.000000,4821.000000,5057.000000,7820.000000,6068.000000,3823.000000
75%,5654.000000,6260.500000,8559.500000,8080.000000,6787.500000,5257.500000,8147.500000,5977.500000,5953.500000,5990.000000,5667.750000,7409.500000,5803.000000,6691.000000,9313.000000,7647.500000,4613.500000
max,9775.000000,9122.000000,12389.000000,11720.000000,10675.000000,8578.000000,14676.000000,10034.000000,9755.000000,8852.000000,10419.000000,11731.000000,9631.000000,11276.000000,15888.000000,12838.000000,7730.000000

In [13]:
# Get a concise summary of the DataFrame, including data types and non-null counts
primary_market_transaction_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Quarter       71 non-null     object
 1   Bialystok     71 non-null     float64
 2   Bydgoszcz     71 non-null     float64
 3   Gdansk        71 non-null     float64
 4   Gdynia        71 non-null     float64
 5   Katowice      71 non-null     float64
 6   Kielce        71 non-null     float64
 7   Krakow        71 non-null     float64
 8   Lublin        71 non-null     float64
 9   Lodz          71 non-null     float64
 10  Olsztyn       71 non-null     float64
 11  Opole         70 non-null     float64
 12  Poznan        71 non-null     float64
 13  Rzeszow       71 non-null     float64
 14  Szczecin      71 non-null     float64
 15  Warsaw        71 non-null     float64
 16  Wroclaw       71 non-null     float64
 17  Zielona Gora  71 non-null     float64
dtypes: float64(17), object(1)
memory usage: 10.1+ KB

In [14]:
# Generate a statistical summary of the numerical columns in the DataFrame
secondary_market_transaction_prices_df.describe()

,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,4803.183099,4324.056338,6819.056338,6347.774648,4155.746479,4312.633803,7253.929577,5319.732394,4290.098592,4882.169014,4511.464789,6034.169014,5241.788732,4899.647887,8961.802817,6531.239437,3818.112676
std,1345.646486,1162.248521,2188.298138,1792.111007,1192.737700,998.987162,1920.560732,1328.573402,1203.967265,1067.091561,1169.708753,1391.333040,1547.348201,1423.721513,2012.924636,1721.042454,1246.887743
min,2529.000000,2359.000000,3926.000000,2782.000000,2028.000000,2355.000000,5193.000000,2769.000000,1905.000000,3126.000000,2777.000000,3332.000000,2591.000000,2888.000000,6232.000000,4734.000000,1960.000000
25%,3992.000000,3551.500000,5305.500000,5078.000000,3426.000000,3704.000000,6051.500000,4578.000000,3453.000000,4126.500000,3762.000000,5126.500000,4362.500000,3965.000000,7431.500000,5373.500000,3075.500000
50%,4301.000000,3866.000000,5952.000000,5799.000000,3622.000000,3982.000000,6349.000000,4879.000000,3870.000000,4510.000000,3949.000000,5496.000000,4547.000000,4321.000000,8406.000000,5891.000000,3222.000000
75%,5315.500000,5072.500000,8093.500000,7340.500000,4822.000000,4440.000000,7530.500000,5656.000000,4789.000000,5277.000000,5018.000000,6556.000000,5719.500000,5442.000000,9634.500000,7081.500000,4392.000000
max,8452.000000,7249.000000,12148.000000,10588.000000,7526.000000,7287.000000,13358.000000,8822.000000,7496.000000,7709.000000,7934.000000,9877.000000,9457.000000,8820.000000,14380.000000,11594.000000,7104.000000

In [15]:
# Get a concise summary of the DataFrame, including data types and non-null counts
secondary_market_transaction_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Quarter       71 non-null     object
 1   Bialystok     71 non-null     float64
 2   Bydgoszcz     71 non-null     float64
 3   Gdansk        71 non-null     float64
 4   Gdynia        71 non-null     float64
 5   Katowice      71 non-null     float64
 6   Kielce        71 non-null     float64
 7   Krakow        71 non-null     float64
 8   Lublin        71 non-null     float64
 9   Lodz          71 non-null     float64
 10  Olsztyn       71 non-null     float64
 11  Opole         71 non-null     float64
 12  Poznan        71 non-null     float64
 13  Rzeszow       71 non-null     float64
 14  Szczecin      71 non-null     float64
 15  Warsaw        71 non-null     float64
 16  Wroclaw       71 non-null     float64
 17  Zielona Gora  71 non-null     float64
dtypes: float64(17), object(1)
memory usage: 10.1+ KB

In [16]:
# Generate a statistical summary of the numerical columns in the DataFrame
secondary_market_offer_prices_df.describe()

,Bialystok,Bydgoszcz,Gdansk,Gdynia,Katowice,Kielce,Krakow,Lublin,Lodz,Olsztyn,Opole,Poznan,Rzeszow,Szczecin,Warsaw,Wroclaw,Zielona Gora
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,5422.056338,4684.070423,7937.436620,7762.845070,4811.619718,4818.478873,8355.028169,5740.887324,4880.647887,5247.464789,4888.549296,6772.704225,5713.535211,5367.253521,10308.394366,7332.507042,4248.647887
std,1505.224690,1273.149484,2410.562387,1676.632438,1307.339746,1074.303241,2270.732550,1463.795356,1235.244928,1178.241909,1199.355741,1584.408744,1566.293594,1372.674769,2071.330473,1795.307287,1397.380407
min,3070.000000,2530.000000,4541.000000,5756.000000,2508.000000,2425.000000,6489.000000,3160.000000,2740.000000,3414.000000,3164.000000,3752.000000,2851.000000,3190.000000,7179.000000,5261.000000,2137.000000
25%,4572.000000,3883.500000,6258.000000,6503.000000,3973.500000,4187.500000,6848.000000,4957.500000,4013.500000,4440.000000,4152.000000,5830.500000,4796.000000,4422.000000,8773.000000,6132.500000,3447.000000
50%,4738.000000,4153.000000,6608.000000,6960.000000,4173.000000,4469.000000,7206.000000,5073.000000,4457.000000,4728.000000,4246.000000,6093.000000,4953.000000,4860.000000,9679.000000,6602.000000,3533.000000
75%,5928.500000,5341.000000,9924.500000,8676.500000,5524.500000,4938.000000,9011.000000,6068.000000,5297.500000,5605.000000,5432.500000,7413.500000,6397.500000,5821.500000,11004.000000,7646.000000,4810.000000
max,10184.000000,8047.000000,14064.000000,12245.000000,8037.000000,8213.000000,16417.000000,9852.000000,8555.000000,8766.000000,8671.000000,11719.000000,10282.000000,9247.000000,17546.000000,13226.000000,8198.000000

In [17]:
# Get a concise summary of the DataFrame, including data types and non-null counts
secondary_market_offer_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Quarter       71 non-null     object
 1   Bialystok     71 non-null     float64
 2   Bydgoszcz     71 non-null     float64
 3   Gdansk        71 non-null     float64
 4   Gdynia        71 non-null     float64
 5   Katowice      71 non-null     float64
 6   Kielce        71 non-null     float64
 7   Krakow        71 non-null     float64
 8   Lublin        71 non-null     float64
 9   Lodz          71 non-null     float64
 10  Olsztyn       71 non-null     float64
 11  Opole         71 non-null     float64
 12  Poznan        71 non-null     float64
 13  Rzeszow       71 non-null     float64
 14  Szczecin      71 non-null     float64
 15  Warsaw        71 non-null     float64
 16  Wroclaw       71 non-null     float64
 17  Zielona Gora  71 non-null     float64
dtypes: float64(17), object(1)
memory usage: 10.1+ KB

In [18]:
# Melt the DataFrame from wide format to long format
primary_market_offer_prices_df_melted = primary_market_offer_prices_df.melt(
    id_vars=['Quarter'],  # Column(s) to keep as identifier variables
    var_name='City',      # Name for the new column that will contain former column names
    value_name='Offer Price'  # Name for the new column that will contain former column values
)

# Display the melted DataFrame
primary_market_offer_prices_df_melted

       Quarter          City  Offer Price
0     III 2006     Bialystok       2727.0
1      IV 2006     Bialystok       2727.0
2       I 2007     Bialystok       4181.0
3      II 2007     Bialystok       4725.0
4     III 2007     Bialystok       4199.0
...        ...           ...          ...
1202    I 2023  Zielona Gora       7448.0
1203   II 2023  Zielona Gora       7562.0
1204  III 2023  Zielona Gora       7602.0
1205   IV 2023  Zielona Gora       7853.0
1206    I 2024  Zielona Gora       8165.0

[1207 rows x 3 columns]

In [19]:
# Melt the DataFrame from wide format to long format
primary_market_transaction_prices_df_melted = primary_market_transaction_prices_df.melt(
    id_vars=['Quarter'],            # Column(s) to keep as identifier variables
    var_name='City',               # Name for the new column that will contain former column names
    value_name='Transaction Price'  # Name for the new column that will contain former column values
)

# Display the melted DataFrame
primary_market_transaction_prices_df_melted

       Quarter          City  Transaction Price
0     III 2006     Bialystok             3008.0
1      IV 2006     Bialystok             3117.0
2       I 2007     Bialystok             3500.0
3      II 2007     Bialystok             4422.0
4     III 2007     Bialystok             4651.0
...        ...           ...                ...
1202    I 2023  Zielona Gora             7566.0
1203   II 2023  Zielona Gora             7473.0
1204  III 2023  Zielona Gora             7615.0
1205   IV 2023  Zielona Gora             7655.0
1206    I 2024  Zielona Gora             7730.0

[1207 rows x 3 columns]

In [20]:
# Melt the DataFrame from wide format to long format
secondary_market_offer_prices_df_melted = secondary_market_offer_prices_df.melt(
    id_vars=['Quarter'],            # Columns to keep as identifier variables
    var_name='City',               # Name for the new column that will contain former column names
    value_name='Offer Price'       # Name for the new column that will contain former column values
)

# Display the melted DataFrame
secondary_market_offer_prices_df_melted

       Quarter          City  Offer Price
0     III 2006     Bialystok       3070.0
1      IV 2006     Bialystok       3408.0
2       I 2007     Bialystok       3986.0
3      II 2007     Bialystok       4418.0
4     III 2007     Bialystok       4580.0
...        ...           ...          ...
1202    I 2023  Zielona Gora       7200.0
1203   II 2023  Zielona Gora       7260.0
1204  III 2023  Zielona Gora       7284.0
1205   IV 2023  Zielona Gora       7573.0
1206    I 2024  Zielona Gora       8198.0

[1207 rows x 3 columns]

In [21]:
# Melt the DataFrame from wide format to long format
secondary_market_transaction_prices_df_melted = secondary_market_transaction_prices_df.melt(
    id_vars=['Quarter'],            # Columns to keep as identifier variables
    var_name='City',               # Name for the new column that will contain former column names
    value_name='Transaction Price' # Name for the new column that will contain former column values
)

# Display the melted DataFrame
secondary_market_transaction_prices_df_melted

       Quarter          City  Transaction Price
0     III 2006     Bialystok             2529.0
1      IV 2006     Bialystok             2998.0
2       I 2007     Bialystok             3590.0
3      II 2007     Bialystok             4009.0
4     III 2007     Bialystok             4635.0
...        ...           ...                ...
1202    I 2023  Zielona Gora             6496.0
1203   II 2023  Zielona Gora             6538.0
1204  III 2023  Zielona Gora             6688.0
1205   IV 2023  Zielona Gora             7067.0
1206    I 2024  Zielona Gora             7104.0

[1207 rows x 3 columns]

In [22]:
# Create a line plot using Plotly Express
fig_primary_offer = px.line(
    primary_market_offer_prices_df_melted,  # DataFrame containing the data
    x='Quarter',                           # Column to be used for the x-axis
    y='Offer Price',                       # Column to be used for the y-axis
    color='City',                          # Column to be used for coloring lines
    title='Offer Prices of Real Estate in the Primary Market in Poland (PLN/m²)'  # Title of the plot
)

# Update layout of the figure
fig_primary_offer.update_layout(
    xaxis=dict(
        tickangle=-90  # Rotate x-axis labels for better readability
    ),
    legend=dict(
        yanchor="top",               # Position the legend at the top
        y=1.0,                       # Vertical position of the legend
        xanchor="left",              # Horizontal alignment of the legend
        x=1.0,                       # Horizontal position of the legend
        font=dict(size=10),          # Font size of the legend text
        traceorder="normal",         # Order of traces in the legend
        itemsizing='constant'        # Ensure all items in the legend are of constant size
    )
)

# Show the plot
fig_primary_offer.show()

In [23]:
# Create a line plot using Plotly Express
fig_primary_transaction = px.line(
    primary_market_transaction_prices_df_melted,  # DataFrame containing the data
    x='Quarter',                                # Column to be used for the x-axis
    y='Transaction Price',                      # Column to be used for the y-axis
    color='City',                               # Column to be used for coloring lines
    title='Transaction Prices of Real Estate in the Primary Market in Poland (PLN/m²)'  # Title of the plot
)

# Update layout of the figure
fig_primary_transaction.update_layout(
    xaxis=dict(
        tickangle=-90  # Rotate x-axis labels for better readability
    ),
    legend=dict(
        yanchor="top",               # Position the legend at the top
        y=1.0,                       # Vertical position of the legend
        xanchor="left",              # Horizontal alignment of the legend
        x=1.0,                       # Horizontal position of the legend
        font=dict(size=10),          # Font size of the legend text
        traceorder="normal",         # Order of traces in the legend
        itemsizing='constant'        # Ensure all items in the legend are of constant size
    )
)

# Show the plot
fig_primary_transaction.show()

In [24]:
# Create a line plot using Plotly Express
fig_secondary_offer = px.line(
    secondary_market_offer_prices_df_melted,  # DataFrame containing the melted data
    x='Quarter',                            # Column to be used for the x-axis
    y='Offer Price',                        # Column to be used for the y-axis
    color='City',                           # Column to be used for coloring lines
    title='Offer Prices of Real Estate in the Secondary Market in Poland (PLN/m²)'  # Title of the plot
)

# Update layout of the figure
fig_secondary_offer.update_layout(
    xaxis=dict(
        tickangle=-90  # Rotate x-axis labels for better readability
    ),
    legend=dict(
        yanchor="top",               # Position the legend at the top
        y=1.0,                       # Vertical position of the legend
        xanchor="left",              # Horizontal alignment of the legend
        x=1.0,                       # Horizontal position of the legend
        font=dict(size=10),          # Font size of the legend text
        traceorder="normal",         # Order of traces in the legend
        itemsizing='constant'        # Ensure all items in the legend are of constant size
    )
)

# Show the plot
fig_secondary_offer.show()

In [25]:
# Create a line plot using Plotly Express
fig_secondary_transaction = px.line(
    secondary_market_transaction_prices_df_melted,  # DataFrame containing the melted data
    x='Quarter',                                 # Column to be used for the x-axis
    y='Transaction Price',                       # Column to be used for the y-axis
    color='City',                                # Column to be used for coloring lines
    title='Transaction Prices of Real Estate in the Secondary Market in Poland (PLN/m²)'  # Title of the plot
)

# Update layout of the figure
fig_secondary_transaction.update_layout(
    xaxis=dict(
        tickangle=-90  # Rotate x-axis labels for better readability
    ),
    legend=dict(
        yanchor="top",               # Position the legend at the top
        y=1.0,                       # Vertical position of the legend
        xanchor="left",              # Horizontal alignment of the legend
        x=1.0,                       # Horizontal position of the legend
        font=dict(size=10),          # Font size of the legend text
        traceorder="normal",         # Order of traces in the legend
        itemsizing='constant'        # Ensure all items in the legend are of constant size
    )
)

# Show the plot
fig_secondary_transaction.show()

In [26]:
# Merge the offer prices and transaction prices DataFrames on 'Quarter' and 'City'
primary_market_df = pd.merge(
    primary_market_offer_prices_df_melted,      # First DataFrame containing offer prices
    primary_market_transaction_prices_df_melted,  # Second DataFrame containing transaction prices
    how='inner',                               # Merge method: only include rows with matching keys in both DataFrames
    on=['Quarter', 'City']                     # Columns to merge on: 'Quarter' and 'City'
)

# Display the resulting merged DataFrame
primary_market_df

       Quarter          City  Offer Price  Transaction Price
0     III 2006     Bialystok       2727.0             3008.0
1      IV 2006     Bialystok       2727.0             3117.0
2       I 2007     Bialystok       4181.0             3500.0
3      II 2007     Bialystok       4725.0             4422.0
4     III 2007     Bialystok       4199.0             4651.0
...        ...           ...          ...                ...
1202    I 2023  Zielona Gora       7448.0             7566.0
1203   II 2023  Zielona Gora       7562.0             7473.0
1204  III 2023  Zielona Gora       7602.0             7615.0
1205   IV 2023  Zielona Gora       7853.0             7655.0
1206    I 2024  Zielona Gora       8165.0             7730.0

[1207 rows x 4 columns]

In [27]:
# Extract a list of unique cities from the 'City' column
city_list = list(primary_market_offer_prices_df_melted['City'].drop_duplicates())
city_list

['Bialystok',
 'Bydgoszcz',
 'Gdansk',
 'Gdynia',
 'Katowice',
 'Kielce',
 'Krakow',
 'Lublin',
 'Lodz',
 'Olsztyn',
 'Opole',
 'Poznan',
 'Rzeszow',
 'Szczecin',
 'Warsaw',
 'Wroclaw',
 'Zielona Gora']

In [28]:
# Initialize the Dash app
first_dash_app = dash.Dash()

# Define the layout of the app
first_dash_app.layout = html.Div([
    # Title of the app
    html.Div([
        html.H1('Prices on the primary market in Poland')
    ]),
    # Dropdown for selecting a city
    html.P("Choose a city:"),
    dcc.Dropdown(
        id='city',
        options=[{'value': str(city), 'label': city}
                 for city in city_list],  # Populate dropdown options with city names
        value=city_list[-3]  # Default selected value (the third-to-last city in the list)
    ),
    html.Br(),
    # Two graphs to display data
    html.Div(children=[
        dcc.Graph(id="graph-1", style={'display': 'inline-block', 'width': '48%'}),
        dcc.Graph(id="graph-2", style={'display': 'inline-block', 'width': '48%'})
    ])
])

In [29]:
@first_dash_app.callback(
    Output(component_id='graph-1', component_property='figure'),  # Output: Graph 1's figure property
    Input(component_id='city', component_property='value')        # Input: City dropdown's value property
)
def generate_first_graph(city):
    # Filter the DataFrame to include only data for the selected city
    df = primary_market_df[primary_market_df['City'] == city]

    # Create a line plot with Plotly Express
    fig = px.line(
        data_frame=df,
        x='Quarter',  # X-axis: Quarter
        y='Transaction Price',  # Y-axis: Transaction Price
        title=f'Transaction prices per 1m² of apartment in {city}',  # Title of the plot
    )

    return fig

In [30]:
@first_dash_app.callback(
    Output(component_id='graph-2', component_property='figure'),  # Output: Graph 2's figure property
    Input(component_id='city', component_property='value')        # Input: City dropdown's value property
)
def generate_second_graph(city):
    # Filter the DataFrame to include only data for the selected city
    df = primary_market_df[primary_market_df['City'] == city]

    # Create a line plot with Plotly Express
    fig = px.line(
        data_frame=df,
        x='Quarter',  # X-axis: Quarter
        y='Offer Price',  # Y-axis: Offer Price
        title=f'Offer prices per 1m² of apartment in {city}',  # Title of the plot
    )

    return fig

In [39]:
# Create and start a new thread to run the Dash server
# `first_dash_app.run_server` is the function that starts the Dash server.
# Running it in a separate thread allows the notebook to remain interactive.
thread = threading.Thread(target=first_dash_app.run_server)

# Start the thread, which begins running the Dash server in the background
thread.start()

# Display the server port in the Colab notebook
# `output.serve_kernel_port_as_window(port=8050)` creates a link to access the Dash app.
# Port 8050 is the default port for Dash applications; adjust if your app uses a different port.
output.serve_kernel_port_as_window(port=8050)

In [38]:
# Merge the two DataFrames on 'Quarter' and 'City' to combine offer prices and transaction prices
secondary_market_df = pd.merge(
    secondary_market_offer_prices_df_melted,  # DataFrame containing offer prices
    secondary_market_transaction_prices_df_melted,  # DataFrame containing transaction prices
    how='inner',  # Type of merge: 'inner' means only include rows with matching values in both DataFrames
    on=['Quarter', 'City']  # Columns to merge on
)

# Display the merged DataFrame to check the result
secondary_market_df

       Quarter          City  Offer Price  Transaction Price
0     III 2006     Bialystok       3070.0             2529.0
1      IV 2006     Bialystok       3408.0             2998.0
2       I 2007     Bialystok       3986.0             3590.0
3      II 2007     Bialystok       4418.0             4009.0
4     III 2007     Bialystok       4580.0             4635.0
...        ...           ...          ...                ...
1202    I 2023  Zielona Gora       7200.0             6496.0
1203   II 2023  Zielona Gora       7260.0             6538.0
1204  III 2023  Zielona Gora       7284.0             6688.0
1205   IV 2023  Zielona Gora       7573.0             7067.0
1206    I 2024  Zielona Gora       8198.0             7104.0

[1207 rows x 4 columns]

In [33]:
# Initialize a new Dash app
second_dash_app = dash.Dash()

# Define the layout of the Dash app
second_dash_app.layout = html.Div([
    # Main title of the app
    html.Div([
        html.H1('Prices on the secondary market in Poland')
    ]),
    # Dropdown to select a city
    html.P("Choose a city:"),
    dcc.Dropdown(
        id='city',  # Identifier for the dropdown component
        options=[{'value': str(city), 'label': city}
                 for city in city_list],  # List of cities for the dropdown options
        value=city_list[-3]  # Default value for the dropdown (third last city in the list)
    ),
    html.Br(),  # Line break for spacing
    # Container for the graphs
    html.Div(children=[
        dcc.Graph(id="graph-3", style={'display': 'inline-block', 'width': '48%'}),  # Graph for offer prices
        dcc.Graph(id="graph-4", style={'display': 'inline-block', 'width': '48%'})   # Graph for transaction prices
    ])
])

In [34]:
# Define a callback function to update 'graph-3' based on the selected city
@second_dash_app.callback(
    Output(component_id='graph-3', component_property='figure'),  # The output component is the 'figure' property of 'graph-3'
    Input(component_id='city', component_property='value')  # The input component is the 'value' property of the 'city' dropdown
)
def generate_third_graph(city):
    # Filter the secondary_market_df DataFrame to include only rows where the 'City' matches the selected city
    df = secondary_market_df[secondary_market_df['City'] == city]

    # Create a line plot using Plotly Express
    fig = px.line(
        data_frame=df,  # DataFrame to be used for plotting
        x='Quarter',  # X-axis will represent the 'Quarter'
        y='Transaction Price',  # Y-axis will represent the 'Transaction Price'
        title=f'Transaction prices per 1m² of apartment in {city}',  # Title of the plot, dynamically updated with the selected city
    )

    # Return the figure object to be displayed in 'graph-3'
    return fig

In [35]:
# Define a callback function to update 'graph-4' based on the selected city
@second_dash_app.callback(
    Output(component_id='graph-4', component_property='figure'),  # The output component is the 'figure' property of 'graph-4'
    Input(component_id='city', component_property='value')  # The input component is the 'value' property of the 'city' dropdown
)
def generate_fourth_graph(city):
    # Filter the secondary_market_df DataFrame to include only rows where the 'City' matches the selected city
    df = secondary_market_df[secondary_market_df['City'] == city]

    # Create a line plot using Plotly Express for the offer prices
    fig = px.line(
        data_frame=df,  # DataFrame to be used for plotting
        x='Quarter',  # X-axis will represent the 'Quarter'
        y='Offer Price',  # Y-axis will represent the 'Offer Price'
        title=f'Offer prices per 1m² of apartment in {city}'  # Title of the plot, dynamically updated with the selected city
    )

    # Return the figure object to be displayed in 'graph-4'
    return fig

In [37]:
# Create a new thread to run the Dash server for the secondary market app
# `second_dash_app.run_server` is the method that starts the Dash server.
thread = threading.Thread(target=second_dash_app.run_server)

# Start the thread to begin running the Dash server in the background
# This allows the notebook to remain interactive and execute other code while the server is running.
thread.start()

# Display the server port in the Colab notebook
# `output.serve_kernel_port_as_window(port=8051)` creates a link to access the Dash app.
# Ensure that the port number here matches the port specified in the Dash server setup (8051).
output.serve_kernel_port_as_window(port=8051)